Added get messages method
Code-Collaborate-Community/tiger pull request #114
Opened 2019-12-23 13:51 UTC by morbitton

#91 

@lioramilbaum @Yarinh55 
Hi, it's the base , because the database didn't merge yet

2019-12-24 20:56 UTC, lioramilbaum commented
@morbitton db PRs are merged. Go ahead and verify your code. Add tests to travis please.

2019-12-24 20:57 UTC, lmilbaum requested changes
pull latest changes from upstream, rebase
add tests to travis

2019-12-30 11:59 UTC, AviadP requested changes

2019-12-30 11:59 UTC, AviadP commented on connect.py
> +
you must use functions here. without it you file will not be useful to others

2019-12-30 11:59 UTC, AviadP commented on connect.py
> +print(mydb)
debug printing shell not be pushed to production

2019-12-30 11:59 UTC, AviadP commented on connect.py
> +print(mydb)
also, python have easy to use log module, which is much better for debugging purposes (in this case, you can leave it in production with proper printing level - Debug, Error, Info etc.)

2020-01-05 09:05 UTC, lioramilbaum commented
@morbitton what is the status of this PR?

2020-01-05 09:29 UTC, morbitton commented
need to fix the problem with travis and upload

2020-01-05 09:30 UTC, lioramilbaum commented
OK. Awaiting for those changes. LMK if you are blocked or not.

2020-01-05 17:49 UTC, morbitton commented
closed, open new one

2020-01-05 17:50 UTC, closed without merging