[view message] Added get messages method #91
Code-Collaborate-Community/tiger pull request #128
Opened 2020-01-05 17:51 UTC by morbitton

fix #91

2020-01-06 07:40 UTC, lioramilbaum commented
Should I add Yarin to the list of assignees? If yes, than should add a comment here.

2020-01-06 09:11 UTC, lioramilbaum commented
@morbitton I am confused. Is this PR WIP or is it ready for review?

2020-01-06 10:19 UTC, Yarinh55 commented
Hi @lioramilbaum 
we worked together on this PR
It's ready to review and we will add another PR to finish issue #91 after you will approve the messages_view.html #119

2020-01-06 12:27 UTC, lmilbaum requested changes
1. This PR has conflicts. Please resolve them.
2. If this PR is a partial fix of  #91, than break it to smaller issues.

2020-01-06 15:26 UTC, lmilbaum requested changes
log.log should not be tracked by git. Add it to .gitignore and remove it from this PR.

2020-01-06 16:34 UTC, morbitton commented
@lioramilbaum @Yarinh55 
We insert log.log file to .gitignore but we still see the file.
Did we understand u well?

2020-01-07 12:49 UTC, lmilbaum requested changes
Adding the file to gitignore does not change after the fact. If you already tracked by git, than gitignore does NOT influence. You should remove the file from the PR. Google it.

2020-01-07 13:50 UTC, morbitton commented
@lioramilbaum 
i think its ok now

2020-01-07 15:22 UTC, lmilbaum requested changes
what those swo and swp files for?

2020-01-07 15:36 UTC, morbitton commented
when we change at the VI file git open those. Nikita said to change file in another way. and we remove those files @lioramilbaum

2020-01-07 15:59 UTC, lmilbaum requested changes

2020-01-07 15:59 UTC, lioramilbaum commented on app.py
> +# import app_functions
remove comment line

2020-01-07 15:59 UTC, lioramilbaum commented on app.py
> +    # print(row)
remove comment

2020-01-07 16:07 UTC, morbitton commented on app.py
> +# import app_functions
delete for now because the file delete

2020-01-07 16:08 UTC, morbitton commented on app.py
> +    # print(row)
done

2020-01-07 16:24 UTC, lmilbaum approved these changes
LGTM

2020-01-07 16:24 UTC, lmilbaum requested changes
Have you pulled the latest changes and rebased?

2020-01-07 16:40 UTC, morbitton commented
yes , everytime Im get the git i run the comment "git pull upstream"

2020-01-07 16:49 UTC, lioramilbaum commented
You need to pull from upstream master and then rebase your branch

2020-01-07 17:06 UTC, morbitton commented
now i see there is conflict, 
work on it and let u know as we finish , sorry

2020-01-08 08:56 UTC, lmilbaum approved these changes
LGTM

2020-01-08 08:57 UTC, lmilbaum requested changes
still conflicts

2020-01-08 11:18 UTC, morbitton commented
![image](https://user-images.githubusercontent.com/57069656/71974082-44ea5300-3219-11ea-9025-cb0a73e9f09f.png)

@lioramilbaum run all the conflict. git said to me im Successfully rebased and updated refs/heads/test.

2020-01-08 11:20 UTC, lioramilbaum commented
Look at the instructions I have posted in Sahar's PR.

2020-01-12 11:14 UTC, closed without merging