Added license file
Code-Collaborate-Community/tiger pull request #15
Opened 2019-11-13 11:42 UTC by Nomasson

2019-11-13 17:48 UTC, lmilbaum requested changes
The name of the file should be LICENSE.md according to GitHub:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

2019-11-13 17:49 UTC, lioramilbaum commented
Please add a reference to the issue number

2019-11-15 10:39 UTC, igoihman commented
@Nomasson please add this sentence in the pull request description: Fixes #<issue_number>

2019-11-16 15:46 UTC, lmilbaum approved these changes

2019-11-16 15:48 UTC, merged