Issue #37 Add a Subscribe page
Code-Collaborate-Community/tiger pull request #53
Opened 2019-11-26 10:39 UTC by shirmenzely

By Ron Biton and Shir Menzely

2019-11-30 08:38 UTC, lmilbaum requested changes
Go over all the code review comments provided today. And find out what is relevant for this PR.

2019-11-30 08:38 UTC, lioramilbaum commented on Subscribe page.py
> +from flask import Flask, request, render_template
The subscribe page should be and addition to the current app, not another app with a subscribe page

2019-12-01 18:47 UTC, lioramilbaum commented
@shirmenzely we have a new contact_us page. Have a look.  It might be a duplicate of this work.

2019-12-03 19:11 UTC, shirmenzely commented
> @shirmenzely we have a new contact_us page. Have a look. It might be a duplicate of this work.

I think the essence of the pages is different. On the contact page users leave a message, while on the second page they subscribe for updates

2019-12-14 16:48 UTC, lioramilbaum commented
Is this PR still relevant or we can close it?

2019-12-24 19:15 UTC, closed without merging