MySql deployment
Code-Collaborate-Community/tiger pull request #55
Opened 2019-11-30 13:01 UTC by BarakMerdler

fix #12

2019-11-30 15:42 UTC, BarakMerdler commented
adding to bootstrap.sh script to run MySQL
Adding txt file for config .rpm
changed memory to 1024 to run MySQL
#12

2019-12-01 06:52 UTC, lmilbaum requested changes

2019-12-01 06:52 UTC, lioramilbaum commented on Vagrantfile
> +  config.vm.provision "file", source: "scripts/start-sql-config.txt", destination: "/tmp/start-sql-config.txt"
You do not need that. All files are synced to guest into '/vagrant' directory

2019-12-01 06:52 UTC, lioramilbaum commented on scripts/bootstrap.sh
> +mv /tmp/start-sql-config.txt /etc/yum.repos.d/mysql-community.repo
Again, you don't need this 2 step action. The file - mysq-community.repo can be found in /vagrant during provisioning.

2019-12-01 06:52 UTC, lioramilbaum commented on scripts/bootstrap.sh
> +dnf -y install mysql-community-server
You can "merge" this line with line 7 and move the systemctl commands after line 7.

2019-12-01 09:09 UTC, BarakMerdler commented
@lioramilbaum commit changes after the last review.
delete the `config.vm.provision "file"` from vagrantfile
moved the mysq-community.repo to /vagrant
merged installation mysql with python3-pip

2019-12-01 18:23 UTC, lmilbaum approved these changes
LGTM

2019-12-01 18:23 UTC, merged