Add layout file with navbar
Code-Collaborate-Community/tiger pull request #57
Opened 2019-11-30 20:55 UTC by Yarinh55

fix #27

2019-11-30 21:37 UTC, lmilbaum requested changes
I can't see the navbar.  You should render html file when browsing to home page

2019-11-30 21:54 UTC, lioramilbaum commented
How did you test this PR?

2019-11-30 21:57 UTC, Yarinh55 commented
@lioramilbaum 
sorry, my mistake. 
I miss it at push to GH

2019-12-01 06:12 UTC, lmilbaum requested changes

2019-12-01 06:12 UTC, lioramilbaum commented on Vagrantfile
> +end
how this change relates to this PR?

2019-12-01 06:12 UTC, lioramilbaum commented on app.py
> +@app.route('/')
This change is also unrelated. Remove it.

2019-12-01 16:52 UTC, closed without merging